package template

const (
	genEntityCustom = `
package {{.EntityPackageName}}

func (entity *{{.EntityStructName}}) ToBizStruct() *{{.BizStructName}} {
	panic("Unrealized methods!!!")
}

func (entity *{{.EntityStructName}}) FromBizStruct(data *{{.BizStructName}}) {
	panic("Unrealized methods!!!")
}

func (entity *{{.EntityStructName}}) BeforeCreate(conn *gorm.DB) error {
    // conn.Statement.SetColumn("created_at", time.Now())
    return nil
}

func (entity *{{.EntityStructName}}) BeforeUpdate(conn *gorm.DB) (err error) {
    // 如果任意字段有变更
    // if conn.Statement.Changed() {
    //     conn.Statement.SetColumn("updated_at", time.Now())
    // }
    return nil
}

func (entity *{{.EntityStructName}}) BeforeDelete(conn *gorm.DB) (err error) {
    return nil
}


`

	genRepoBase = `
// Package {{.RepoPackageName}} Code generated by kratosgormctl. DO NOT EDIT!
package {{.RepoPackageName}}

import (
    "gorm.io/gorm"
    "time"
    "context"
)

type (
    {{.InnerInterfaceName}} interface {
        Insert(ctx context.Context, data *{{.BizStructName}}) (int64, error)
		FindAfterInsert(ctx context.Context, data *{{.BizStructName}}) (*{{.BizStructName}}, error)
        FindOne(ctx context.Context, id int64, columns ...string) (*{{.BizStructName}}, error)
        Update(ctx context.Context, data *{{.BizStructName}}, columns ...string) error
		FindAfterUpdate(ctx context.Context, data *{{.BizStructName}}, columns ...string) (*{{.BizStructName}}, error)
		Delete(ctx context.Context, data *{{.BizStructName}}) error
    }

    {{.DefaultModelName}} struct {
        *gorm.DB
    }
)

func new{{.OuterInterfaceName}}(conn *gorm.DB) *{{.DefaultModelName}} {
	return &{{.DefaultModelName}}{
		conn,
	}
}

func (m *{{.DefaultModelName}}) Insert(ctx context.Context, data *{{.BizStructName}}) (int64, error) {
	entityData := new({{.EntityPackageName}}.{{.EntityStructName}})
	entityData.FromBizStruct(data)
    err := m.WithContext(ctx).Model(&{{.EntityPackageName}}.{{.EntityStructName}}{}).Create(entityData).Error
    if err != nil {
        return 0, err
    }

    return int64(entityData.ID), nil
}

func (m *{{.DefaultModelName}}) FindAfterInsert(ctx context.Context, data *{{.BizStructName}}) (*{{.BizStructName}}, error) {
	id, err := m.Insert(ctx, data)
	if err != nil {
		return nil, err
	}

	result, err := m.FindOne(ctx, id)
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (m *{{.DefaultModelName}}) FindOne(ctx context.Context, id int64, columns ...string) (*{{.BizStructName}}, error) {
    var data {{.EntityPackageName}}.{{.EntityStructName}}
	var err error
	if len(columns) > 0 {
    	err = m.WithContext(ctx).Model(&{{.EntityPackageName}}.{{.EntityStructName}}{}).Select(columns).First(&data, id).Error
	} else {
		err = m.WithContext(ctx).Model(&{{.EntityPackageName}}.{{.EntityStructName}}{}).First(&data, id).Error
	}
    if err != nil {
        return nil, err
    }

    return (&data).ToBizStruct(), nil
}

func (m *{{.DefaultModelName}}) Update(ctx context.Context, data *{{.BizStructName}}, columns ...string) error {
    if data == nil {
        return nil
    }

	entityData := new({{.EntityPackageName}}.{{.EntityStructName}})
	entityData.FromBizStruct(data)
	
	var err error
	if len(columns) > 0 {
		err = m.WithContext(ctx).Model(&{{.EntityPackageName}}.{{.EntityStructName}}{}).Select(columns).Where("id = ?", entityData.ID).Updates(entityData).Error
	} else{
		err = m.WithContext(ctx).Model(&{{.EntityPackageName}}.{{.EntityStructName}}{}).Where("id = ?", entityData.ID).Updates(entityData).Error
	}

    if err != nil {
        return err
    }

    return nil
}

func (m *{{.DefaultModelName}}) FindAfterUpdate(ctx context.Context, data *{{.BizStructName}}, columns ...string) (*{{.BizStructName}}, error) {
	err := m.Update(ctx, data, columns...)
	if err != nil {
		return nil, err
	}

	entityData := new({{.EntityPackageName}}.{{.EntityStructName}})
	entityData.FromBizStruct(data)
	result, err := m.FindOne(ctx, int64(entityData.ID))
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (m *{{.DefaultModelName}}) Delete(ctx context.Context, data *{{.BizStructName}}) error {
	entityData := new({{.EntityPackageName}}.{{.EntityStructName}})
	entityData.FromBizStruct(data)
	err := m.WithContext(ctx).Delete(entityData).Error
    
    return err
}
`

	genRepoCustom = `package {{.RepoPackageName}}

import (
    "gorm.io/gorm"
)


var _ {{.OuterInterfaceName}} = (*custom{{.OuterInterfaceName}})(nil)

type (
    // {{.OuterInterfaceName}} is an interface to be customized, add more methods here,
    // and implement the added methods in custom{{.OuterInterfaceName}}.
    {{.OuterInterfaceName}} interface {
        {{.InnerInterfaceName}}
    }

    custom{{.OuterInterfaceName}} struct {
        *{{.DefaultModelName}}
    }
)

// New{{.OuterInterfaceName}} returns a model for the database table.
func New{{.OuterInterfaceName}}(conn *gorm.DB) {{.BizRepoName}} {
	return &custom{{.OuterInterfaceName}}{
		default{{.OuterInterfaceName}}: new{{.OuterInterfaceName}}(conn),
	}
}
`
)

type (
	GenBaseStruct struct {
		EntityPackageName  string
		RepoPackageName    string
		InnerInterfaceName string
		OuterInterfaceName string
		DefaultModelName   string
		BizStructName      string
		BizRepoName        string
		EntityStructName   string
		TableName          string
	}
)
